services:
  - type: web
    name: traffic-seo-tool
    runtime: python
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: your-key.json
